POST http://localhost:3000/api/option
Content-Type: application/json

{
  "shotPrice": 500,
  "extraPrice": 700,
  "hot": true
}

###  {
###    "name": "오렌지쥬스",
###    "price": 100,
###    "type": "juice"
###  }