POST http://localhost:3000/api/item
Content-Type: application/json

{
  "name": "에스프레소",
  "price": 1800,
  "type": "coffee",
  "optionId": 3
}

###  {
###    "name": "오렌지쥬스",
###    "price": 100,
###    "type": "juice"
###  }