POST http://localhost:3000/api/order
Content-Type: application/json

{
  "orders": [
    {
      "itemId": 2,
      "amount": 1,
      "option": {
        "shot": 1,
        "extra": true,
        "hot": false
      }
    }
  ]
}